version: "3"
services:
  app: &app
    image: ghcr.io/popamoscow/infomate:${GITHUB_SHA:-latest}
    command: make docker-run-app
    container_name: infomate_app
    environment:
      - VIRTUAL_HOST=news.popa.moscow
      - VIRTUAL_PORT=8816
      - LETSENCRYPT_HOST=news.popa.moscow
      - LETSENCRYPT_EMAIL=news.popa.moscow@raw.email
      - MODE=production
      - PYTHONUNBUFFERED=1
      - DEBUG=false
      - APP_HOST=https://news.popa.moscow
      - POSTGRES_DB=infomate
      - POSTGRES_USER=popamoscow
      - POSTGRES_PASSWORD=popamoscow
      - POSTGRES_HOST=infomate_postgres
    env_file:
      - .env
    restart: always
    ports:
      - "127.0.0.1:8816:8816"

  cron:
    <<: *app
    command: make docker-run-cron
    container_name: infomate_cron
    depends_on:
      - app
    ports: []

  postgres:
    image: postgres:12
    container_name: infomate_postgres
    restart: always
    environment:
      POSTGRES_USER: popamoscow
      POSTGRES_PASSWORD: popamoscow
      POSTGRES_DB: infomate
    volumes:
      - /tmp/pgdata:/var/lib/postgresql/data:rw

  migrate_and_init:
    <<: *app
    container_name: infomate_init_feeds
    restart: "no"
    ports: []
    depends_on:
      - app
    command: make feed_init feed_refresh
